### ISSUE TITLE
Auto remove warning on re-connect

### ISSUE THREAD

**Issue by joente** [thingsdb/ThingsGUI#168] opened 2021-12-02 20:50 UTC
It is nice that a warning appears when the connection is broken. Is it also possible to auto-remove the warning once the connection is re-established?

**Comment by AnjaBruls** [comment] 2021-12-09 15:21
Duplicate of https://github.com/thingsdb/ThingsGUI/issues/149. Changed in release v1.0.0

**Closed by AnjaBruls** 2021-12-09 15:21 UTC
Labels: enhancement
